Repository rureverek/VDSProject, pull requests merged in 2023-11, with the labels that each got.

#4 feat: add Testing CI to Github Actions
  .github/workflows/cmake-single-platform.yml
Labels: enhancement

#1 feat: initial
  .gitignore
  README.md
Labels: documentation, enhancement

#5 feat: added ManagerInterface constructor and BDD_ID table
  src/ManagerInterface.h
  src/test/Tests.h
Labels: enhancement

#6 feat: ManagerInterface - True(), False() methods
  src/Manager.cpp
  src/ManagerInterface.h
  src/test/Tests.h
Labels: enhancement

#12 feat: Add hash map
  .gitignore
  src/Manager.cpp
  src/Manager.h
  src/ManagerInterface.h
  src/test/Tests.h
Labels: enhancement

#13 feat: test fixture
  src/test/Tests.h
Labels: enhancement

#15 doc: Add comments
  src/Manager.cpp
  src/Manager.h
  src/test/Tests.h
Labels: documentation

#17 Top var
  src/Manager.cpp
  src/Manager.h
  src/ManagerInterface.h
  src/test/Tests.h
Labels: enhancement
