Repository rureverek/VDSProject, pull requests merged in 2024-01, with the labels that each got.

#31 feat: part2
  src/Manager.cpp
  src/Manager.h
  src/main.cpp
  src/test/Tests.h
Labels: enhancement

#30 add: benchmark files
  .github/workflows/cmake-single-platform.yml
  benchmarks/README.md
  benchmarks/iscas85/c1355.bench
  benchmarks/iscas85/c17.bench
  benchmarks/iscas85/c1908.bench
  benchmarks/iscas85/c2670.bench
  benchmarks/iscas85/c3540.bench
  benchmarks/iscas85/c432.bench
  benchmarks/iscas85/c499.bench
  benchmarks/iscas85/c5315.bench
  benchmarks/iscas85/c6288.bench
  benchmarks/iscas85/c7552.bench
  benchmarks/iscas85/c880.bench
  src/CMakeLists.txt
  src/bench/BenchParser.cpp
  src/bench/BenchParser.hpp
  src/bench/BenchmarkLib.cpp
  src/bench/BenchmarkLib.h
  src/bench/CMakeLists.txt
  src/bench/CircuitToBDD.cpp
  src/bench/CircuitToBDD.hpp
  src/bench/bench_grammar.hpp
  src/bench/main_bench.cpp
  src/bench/skip_parser.hpp
  src/verify/CMakeLists.txt
  src/verify/main_verify.cpp
Labels: enhancement

#33 doc: init part3 files
  CMakeLists.txt
  doc/VDSCP_Part_3.pdf
  src/CMakeLists.txt
  src/reachability/CMakeLists.txt
  src/reachability/Reachability.cpp
  src/reachability/Reachability.h
  src/reachability/ReachabilityInterface.h
  src/reachability/Tests.h
  src/reachability/main_test.cpp
Labels: documentation

#35 Changed struct of vector
  src/Manager.cpp
  src/Manager.h
Labels: bug

#34 feat: add reachability constructor
  src/reachability/Reachability.cpp
  src/reachability/Reachability.h
  src/reachability/ReachabilityInterface.h
  src/reachability/Tests.h
Labels: enhancement

#36 feat: set_transition_functions()
  src/reachability/Reachability.cpp
  src/reachability/Reachability.h
  src/reachability/Tests.h
Labels: enhancement
